name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/_ci.yml
    with:
      ref: ${{ github.sha }}
      run-build: ${{ github.event_name == 'pull_request' }}
